site_name: my digital home | jlay.us
plugins:
  - git-revision-date
nav:
  - home: index.md
  - projects: projects.md
  - about:
    - blog: blog.md
    - contact: contact.md
    - whoami: whoami.md
theme:
  name: terminal
  palette: dark
  features:
    - revision.date
    - navigation.top.hide
    # - navigation.side.toc.hide  # optiong to disable this per-page
