site_name: jlay.us
plugins:
  - search
  - git-revision-date-localized
nav:
  - home: index.md
  - projects: projects.md
  - about:
    - site: site.md
    - contact: contact.md
    - whoami: whoami.md
theme:
  name: terminal
  palette: dark
  features:
    - revision.date
    - navigation.top.hide
