site_name: jlay.us
plugins:
  - document-dates:
      position: bottom
      show_created: false
      show_author: false
      exclude:
        - index.md
        - '*/index.md'
nav:
  - home: index.md
  - projects: projects.md
  - about:
    - contact: contact.md
    - site: site.md
    - whoami: whoami.md
theme:
  name: terminal
  palette: dark
  features:
    - navigation.top.hide
